### ISSUE TITLE
Add warning when using read_table on a URL from data8/ds8

### ISSUE THREAD

**Issue by SamLau95** [data-8/datascience#184]
In data-8/connector-instructors#13 Andrej ran into a cryptic error when trying to `read_table` on a `data8.berkeley.edu` link.

Since all of those links require authentication, none of them will work with `Table.read_table`. Chris suggested that we give up earlier with a more explicit message when we see one of those links. I think is a good idea as well.

**Comment by deculler** [comment]
It is important that this not be specific to the course.  Can we clarify
what constitutes a path and what it is used for?

David E. Culler
Friesen Professor of Computer Science
Electrical Engineering and Computer Sciences
University of California, Berkeley

**Comment by choldgraf** [comment]
I think the issue is that when you give a URL with the `data8` subdomain, then it passes to the authentication / login screen we usually get when we log in to data8. The `read_table` function doesn't know what to do with it, and so it throws a really cryptic error.

It sounds like for now doing this with the data8 domain will be the most common occurrence of this problem. If there were a way to detect that particular error (some kind of authentication error presumably) then maybe we could catch it and throw a more human-readable message. That might work for arbitrary domain names but I'm not sure how tractable it is to implement.

Another possibility would be to do a really simple try/catch statement, and for *any* error that gets thrown, just say `the URL you gave didn't work, please make sure it is correct and that it points to a data file readable by read_table` or something like that. Not the most elegant solution though.

**Comment by papajohn** [comment]
I like the try/except solution, but the error message should give a hint to the probable cause, which is that the URL requires authentication.

**Comment by choldgraf** [comment]
So I just looked at the `read_table` code and I'm not sure the in its current state we could do a simple try/except solution. This is because the code is already doing try/except. Here are the relevant lines (I think):

```python
        try:
            path = urllib.parse.urlparse(filepath_or_buffer).path
        except AttributeError:
            path = filepath_or_buffer
```

If it fails on the first try, then it assumes that it's working with a file and not a URL. So we'd have to add an except statement for the specific error that gets thrown with an authentication problem. Alternatively, we could add a check in the first try statement, something like:

```python
        try:
            path = urllib.parse.urlparse(filepath_or_buffer).path
            if 'data8.berkeley.edu' in filepath_or_buffer:
                raise ValueError('data8 filepaths require authentication, host your data on a public server')
        except AttributeError:
            path = filepath_or_buffer
```

Thoughts?

**Comment by SamLau95** [comment]
I think this is fine, personally speaking, because:
- We can/should remove it after we put up something to help connector instructors create interact links.
- It doesn't negatively impact people outside the course.

@deculler @papajohn What do you think?

**Comment by papajohn** [comment]
It's fine with me to special case data8.berkeley.edu if it's solving a
problem for some connector.

**Comment by choldgraf** [comment]
See #198 for a PR...LMKWYT
