### ISSUE TITLE
install issue?

### ISSUE THREAD

**Issue by cboettig** [data-8/datascience#212]
Following the instructions on a mac with anaconda for python 3, I get the error: 

```
conda env create -f osx_environment.yml -n datascience
Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Error: No packages found in current osx-64 channels matching: scipy 0.16.1 np110py35_0
```

probably some rookie mistake here.  Linux install instructions worked just fine for me.  Thanks!

**Comment by SamLau95** [comment]
Oops. Should be fixed now.


On March 14, 2016 at 12:20:52 PM, Carl Boettiger (notifications@github.com) wrote:

Following the instructions on a mac with anaconda for python 3, I get the error:

conda env create -f osx_environment.yml -n datascience
Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Error: No packages found in current osx-64 channels matching: scipy 0.16.1 np110py35_0

probably some rookie mistake here. Linux install instructions worked just fine for me. Thanks!

**Comment by cboettig** [comment]
nice, that works. thanks

**Comment by cboettig** [comment]
@SamLau95 After running the above, I try and import the datascience module in Jupyter but I get the error: No module named 'folium'. Any ideas?

**Comment by SamLau95** [comment]
How odd, it looks like folium is specified as a dep in the YAML file.

My guess is that installing from that YAML file gives an environment for working on the datascience package but you might be working in a different environment for Jupyter. Maybe a pip install folium in a notebook cell will fix things for you?



--
Sam Lau
EECS | UC Berkeley
Project Mentor | Blueprint, Technology for Nonprofits
samlau95@gmail.com

On March 14, 2016 at 3:18:04 PM, Carl Boettiger (notifications@github.com) wrote:

@SamLau95 After running the above, I try and import the datascience module in Jupyter but I get the error: No module named 'folium'. Any ideas?

**Comment by cboettig** [comment]
@SamLau95 hmm... I did wonder if it was related to how anaconda is handling environments, but if I don't have datascience environment loaded I get a different error: 'datascience module not found', as expected.

I'm working with a vanilla installation of anaconda:

- installed anconda
- cloned repo, cd into repo, did `conda env create -f osx_environment.yml -n datascience`
- Installed jupyter with `conda install jupyter`.
- ran `source activate datascience` (still in the datascience repo)
- ran `jupyter notebook` (still in datascience repo)

I did try a `conda install folium` but got an error about not knowing which folium package to install.

Can you run `pip install` from inside jupyter?  Is that different than running it in the command-line outside of jupyter? (Sorry, I'm a bit unclear about how the python environment is managed in anconda, I'm used to either full virtualization where it's isolated from my system or a standard linux install where there's basically one global environment for installed modules).

**Comment by SamLau95** [comment]
Huh. That’s strange.

Running pip install inside a Jupyter cell should be equivalent to running it in a terminal, so that’s worth a shot.

If you want to install the development version of datascience (eg. the code that’s in your local folder, not the packaged one from Pypi) you can run make develop in the datascience folder. That works for me, although YMMV.



--
Sam Lau
EECS | UC Berkeley
Project Mentor | Blueprint, Technology for Nonprofits
samlau95@gmail.com

On March 15, 2016 at 11:50:05 AM, Carl Boettiger (notifications@github.com) wrote:

@SamLau95 hmm... I did wonder if it was related to how anaconda is handling environments, but if I don't have datascience environment loaded I get a different error: 'datascience module not found', as expected.

I'm working with a vanilla installation of anaconda:

installed anconda
cloned repo, cd into repo, did conda env create -f osx_environment.yml -n datascience
Installed jupyter with conda install jupyter.
ran source activate datascience (still in the datascience repo)
ran jupyter notebook (still in datascience repo)
I did try a conda install folium but got an error about not knowing which folium package to install.

Can you run pip install from inside jupyter? Is that different than running it in the command-line outside of jupyter? (Sorry, I'm a bit unclear about how the python environment is managed in anconda, I'm used to either full virtualization where it's isolated from my system or a standard linux install where there's basically one global environment for installed modules).

**Comment by flippakitten** [comment]
Same issue here, seems like conda doesn't have a repo for folium, or something.
Anyway, from command line running
`pip install folium` 

fixes the issue for me.

**Comment by sonusuraj** [comment]
ModuleNotFoundError: No module named 'datascience' 

error in windows

**Comment by adnanhemani** [comment]
@sonusuraj just making sure, you have run pip install datascience and it ran without any errors, right?
