### ISSUE TITLE
Table.from_df should have option to keep index

### ISSUE THREAD

**Issue by cboettig** [data-8/datascience#220]
`Table.from_df()` discards the index of a pandas `DataFrame`.  Sometimes that's sensible; e.g. when we convert `Table.to_df()` we just get an arbitrary counter as our index.  In general though the index of a `DataFrame` contains meaningful data (such as dates or factors) that should not be silently discarded.

**Comment by davidwagner** [comment]
Interesting.  Thanks for the suggestion.  Can you elaborate on why this is an important feature to add?  I can see it's easy to add, but I'm just trying to figure out whether adding it to the library is the right thing to do.

One option is to add an option to do this, at the cost of expanding the complexity of the API a little bit.  The other option is to let the caller manually add the index (by  `t = Table.from_df(df)` and `t.append_column('index', df.index.values)`), at the cost of an extra line of code in the caller.  Any time we add to the API we incur a little bit of extra cost of documenting it, maintaining it over time, and the conceptual cost of an extra thing showing up in the docs.  A possible benefit of the caller doing it is that it's more obvious that an extra column will be added and what the column will be labelled.

Can anyone make the case why this ought to be part of the API rather than the second option?   How common is this use case?  For instance, is there a course that would be using this functionality?

**Comment by adnanhemani** [comment]
To be honest, I did this quite mindlessly without thinking if this was a good move. But the only thing that I can think of in terms of why we should implement this into our library is that we don’t want our users to be required to know Pandas syntax (such as df.index.values). In the case that a datascience user imports a Pandas dataframe from somewhere, we want to be able to allow our user to import all the data from the dataframe into datascience.Table (including the index if that’s relevant data too) without having to know Pandas.

Now it’s a different question of why our user would want to import a Pandas DF (or how the non-Pandas user got ahold of the DF to begin with), but I think that’s the use case of the from_df function.

I personally think that the index should be part of the Table when a Pandas DF is imported using from_df, but clearly this isn’t an option due to backwards compatibility issues. Usually the index of the table contains some data that’s relevant to the data set and is not reflected elsewhere in the table (or at least in my experience that’s what I’ve seen).

**Comment by davidwagner** [comment]
OK.  If you update the PR to address the comment, I'll merge it.
