### ISSUE TITLE
Unexpected behavior when plotting

### ISSUE THREAD

**Issue by dfeehan** [data-8/datascience#300]
I'm seeing some weird plotting behavior and it seems like this might be a bug.
 
I'm trying to plot a null distribution with a little red dot on the x axis to help students locate the observed value for a statistic when compared to the simulated null distribution. (They do this in the Data 8 lectures.) However, when I try to add the point to the x axis, it seems to change where on the x axis the distribution is plotted.

Here's an example (to be run in a Jupyter cell):

```
from datascience import *

import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

plt.style.use('fivethirtyeight')

er_r = Table().with_columns('er_r_gender',
     np.array([-0.00028564,  0.00625901, -0.00232185, -0.00723346, -0.00184609,
               -0.00596486,  0.00396077, -0.00612908,  0.00573434,  0.00011851,
               -0.01004085,  0.00118014,  0.00375985,  0.01099454,  0.00761269,
               -0.00908375, -0.01357001, -0.00051094,  0.00171089, -0.01009381]))

observed_r_party = 0.5984762733850006

er_r.hist('er_r_gender')

# uncommenting this line makes the point show up (as desired) 
# but it also seems to change the location of the histogram on the x axis
#plt.scatter(observed_r_party, 0, color='red', s=30);
```

**Comment by adnanhemani** [comment]
Hi @dfeehan, I tried to replicate this issue - it seems like the shifting of the x-axis may be due to the fact that the dot you're plotting is so far to the right of the distribution (in er_r) that the distribution is forced to smoosh the distribution off to the far left to be able to plot the dot on the right. (Which seems about right as the rang of your distribution is (-0.01357001, 0.01099454) and your dot is around 0.6 - a value that's about 30x away from the left edge of your distribution than the right edge of your distribution.

Am I missing something here? If so, please reproduce this issue and screenshot what you see and try to point out on that picture how you think it's not doing what it should be. Thanks!

**Comment by dfeehan** [comment]
I have no memory of this issue, to be honest. It seems fine to close it (to
me). Thanks!
