### ISSUE TITLE
Tests failing because default formatter changed

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#323]
Some of the tests with `make test` are failing, because the default format for numbers changed: instead of displaying numbers as `12345`, the default formatter now displays them as `12,345`.  Is there any reason why this is a problem?  If not, we should just update the tests.

**Comment by papajohn** [comment]
I think we should just update the tests.

**Comment by davidwagner** [comment]
OK.  See PR #331: it should fix this.

**Comment by davidwagner** [comment]
Gaah! It looks like I've just caused problems here.  I tested on my local system but not on Travis, and the two don't behave identically.  Now that PR #331 has been merged, the tests pass on my local build, but they fail on Travis (e.g., https://travis-ci.org/data-8/datascience/builds/430716572).

Looking into this further, it seems to be a difference between Python 3.6 vs 3.7.  With Python 3.6, 123456 gets formatted as `123,456`.  With Python 3.7, it gets formatted as `123456`.  My local system has 3.6 installed.  Travis seems to be using 3.7.  (On the surface `.travis.yml` seems to specify 3.6, but I think using `Miniconda3-latest` overrides that with the latest version of Python, which is now 3.7.)

I apologize.  Rather than fixing a problem, I seem to have created a problem.  How would you like to resolve this?  Should I generate a pull request that reverses the test cases to use the format that will appear on Travis and Python 3.7 (back to where we were before merging PR #331)?

**Comment by deculler** [comment]
We really don't want Tables to be specific to.one version of python.  We
had better fix the test to accept either.

**Comment by davidwagner** [comment]
OK, I'm very confused.  It isn't Python 3.6 vs 3.7 that explains the difference after all.  Still trying to narrow down what is the difference between these two Python environments.  (Current hypothesis: it might be locale-specific.)

**Comment by deculler** [comment]
Yes, they behave differently but we want Tables to be available and pass
its regression tests in either.  We do need to limit what versions we
support, but it would seem we need to accommodate both in the tests.  It is
used far beyond our offering of a course.

**Comment by adnanhemani** [comment]
As is, this library will not even run the tests due to errors in formats.py in Python 3.4. Unsure of how to fix this, but I have confirmed it is an issue with backwards compatibility in py3.4 - when I upgraded my virtual environment to py3.7, this was no longer an issue. Pasting my error code below for future reference:

___________________________________________________ ERROR collecting tests/test_formats.py ____________________________________________________
../../../anaconda3/envs/datascience/lib/python3.4/site-packages/matplotlib/__init__.py:880: in __setitem__
    cval = self.validate[key](val)
E   KeyError: 'patch.force_edgecolor'

During handling of the above exception, another exception occurred:
tests/test_formats.py:3: in <module>
    import datascience as ds
datascience/__init__.py:3: in <module>
    from .tables import *
datascience/tables.py:23: in <module>
    import datascience.util as _util
datascience/util.py:18: in <module>
    plt.rcParams["patch.force_edgecolor"] = True
../../../anaconda3/envs/datascience/lib/python3.4/site-packages/matplotlib/__init__.py:886: in __setitem__
    See rcParams.keys() for a list of valid parameters.' % (key,))
E   KeyError: 'patch.force_edgecolor is not a valid rc parameter.See rcParams.keys() for a list of valid parameters.'
_____________________________________________________ ERROR collecting tests/test_maps.py _____________________________________________________
tests/test_maps.py:5: in <module>
    import datascience as ds
datascience/__init__.py:3: in <module>
    from .tables import *
datascience/tables.py:22: in <module>
    import datascience.formats as _formats
E   AttributeError: 'module' object has no attribute 'formats'
__________________________________________________ ERROR collecting tests/test_predicates.py __________________________________________________
tests/test_predicates.py:3: in <module>
    from datascience import predicates
datascience/__init__.py:3: in <module>
    from .tables import *
datascience/tables.py:22: in <module>
    import datascience.formats as _formats
E   AttributeError: 'module' object has no attribute 'formats'
____________________________________________________ ERROR collecting tests/test_tables.py ____________________________________________________
tests/test_tables.py:6: in <module>
    from datascience import *
datascience/__init__.py:3: in <module>
    from .tables import *
datascience/tables.py:22: in <module>
    import datascience.formats as _formats
E   AttributeError: 'module' object has no attribute 'formats'
_____________________________________________________ ERROR collecting tests/test_util.py _____________________________________________________
tests/test_util.py:3: in <module>
    import datascience as ds
datascience/__init__.py:3: in <module>
    from .tables import *
datascience/tables.py:22: in <module>
    import datascience.formats as _formats
E   AttributeError: 'module' object has no attribute 'formats'

**Comment by davidwagner** [comment]
Fixed by PR #355
