### ISSUE TITLE
Add dtype options to make_array 

### ISSUE THREAD

**Issue by suhailrehman** [data-8/datascience#339]
We had an issue recently in our class where students using windows machines have default int32 types, so allowing for a dtype argument to be passed to the numpy function would be good.

![image](https://user-images.githubusercontent.com/7931270/47114077-7051de00-d220-11e8-81f9-9c62d93d3456.png)

**Comment by adnanhemani** [comment]
@suhailrehman I've made the required changes in #394. Please take a look and let me know if you need any more changes to this! :)

**Comment by davidwagner** [comment]
Ouch.  Annoying.

Unfortunately this solution sounds like it's going to be painful for students, too.  We have to teach them to use `make_array(..., dtype=int64)` everywhere they use `make_array()` to create an array of integers?  So they have to run into it once, ask us why it doesn't work, and then we teach them this workaround, and they have to remember to use it every time?   That sounds painful and like it will still be a bad experience (because they have to run into it once).  It also sounds contrary to the pedagogical goals of the datascience library, where we're trying to not force them to learn this obscure arcane stuff.

I'd like to find a better solution.  Can we instead change this assignment so this issue doesn't come up, by using different numbers?  Or add some custom code to this particular assignment to (somehow) check if they're using windows and if so print a message telling them to use datahub rather than their personal windows machine for this assignment?  That seems feasible.  

Or, if we're going to fix this in the datascience library, probably it would be by having the code of make_array autodetect whether they're creating an array of ints and if so automatically pass dtype=int64, rather than requiring the student to write that code.

**Comment by adnanhemani** [comment]
I agree with you - we shouldn’t have to make students learn this extra argument and why it’s needed.

Based off the OP’s GH profile, I’m guessing that users aren’t at Berkeley and may not have a Datahub of their own. Thus, I’m guessing we should probably engage with the second option and make sure that any array of ints that are passed in should default to int64. It’s quite “magical”, no doubt, but I guess it’ll help with making this library have the same behavior regardless of OS - and to me, “magic” for that is justified. I’ll make the changes and push a new patch onto the same PR soon.

**Comment by suhailrehman** [comment]
Sorry folks, I did not have notifications for Github enabled, and saw your comments just now. Just wanted to convey the pedagoical context for @davidwagner. 

We were teaching this course at UChicago, without datahub, and using the datascience library on students' own machines. Just thought of reporting this issue so that you folks were aware of this potential issue that was OS dependent. I concur with the assessment that adding the dtype option will cause confusion among non-programmers, and the proposed solution works well. 

Thanks for your time folks!
