### ISSUE TITLE
Unintended result for where comparison between a string column label and an array

### ISSUE THREAD

**Issue by sideye** [data-8/datascience#348]
Currently, running a pairwise equality comparison between 2 columns in the form `<tbl>.where(<col label>, <array>)`, will have some unintended consequences in the `_equal_or_float_equal` function, where a value is compared to an array to return a boolean array. Hence, taking the first element of the result of `np.nonzero` on the last line of `where` will run on a 2-D `column` and may have more True's than the intended effect.

The package does not support a pairwise equality comparison between 2 columns in the form `<tbl>.where(<col label>, <array>)`, and instead the correct syntax should be `<tbl>.where(<col label>, are.equal_to, <other col label>)`. However, it is possible to add support for this functionality by adding a check before line 790 (in the elif block where `value_or_predicate` is not None) to see if the 2nd element is an array first:
`if isinstance(value_or_predicate, np.ndarray):`
                
`     predicate = _predicates.are.equal_to`

`     column = [predicate(y)(x) for x, y in zip(column, value_or_predicate)]`

**Comment by adnanhemani** [comment]
We've recently changed the warning on this particular situation [here](https://github.com/data-8/datascience/blob/master/datascience/predicates.py#L254). In order to keep the library as simple as possible and keep the API calls identical (this particular syntax does make sense for equality checking, but we can't make it identical for are.above, are.below, etc.) I'm recommending for a wontfix. @davidwagner, thoughts?

**Comment by davidwagner** [comment]
Agreed.  `.where(col, array)` is something we intend to or should support; it's fine to support it instead by `.where(col, are.equal_to, col2)`, so I'll close this.  Thanks for the idea!
