### ISSUE TITLE
pandas upgrade causes read_table warnings

### ISSUE THREAD

**Issue by ktakimoto** [data-8/datascience#352]
<code>read_table</code> now causes pink warning boxes in notebooks since <code>pd.read_table</code> has been deprecated in favor of <code>pd.read_csv</code>

**Comment by adnanhemani** [comment]
I've done some reading on the Pandas GH, it seems like the read_table method will now be getting [un-deprecated in v0.25.0](https://github.com/pandas-dev/pandas/issues/25220) (release scheduled for 07/01/19). As such, I'd recommend to not make any changes and simply upgrade to the latest version of Pandas when it is released. AFAIK, datahub is running Pandas v0.23.4, so the deprecation warning should not show up there at all.

**Comment by davidwagner** [comment]
Have the pandas folks documented that decision anywhere?  I don't see any decision in that link to the issue over on Pandas to undeprecate read_table.

**Comment by deculler** [comment]
Perhaps we should weigh in on the side of maintain read_table with its
broader notion than csv to help move this to close. ( If read_csv does more
than what it says, so be it.)  A rather discouraging dialog and no clear
conclusion.  Is there a way to suppress the warning while they go back and
forth on this?

**Comment by adnanhemani** [comment]
@davidwagner Yes, if you go to the bottom of the issue that I linked to above, the Pandas folks have added the issue to the v0.25.0 release and the last comment says something similar.

@deculler as far as I know (and based off the testing I’ve done) there is no warning in Datahub at this time (since the version of pandas installed on that server is a couple versions old). Are you seeing this on there or locally?

**Comment by deculler** [comment]
There was datahub warnings during the pedagogy bootcamp last week, but may
been resolved by rollback.  Our dependence is so light that we can
certainly wait this one out and see what they do.

**Comment by davidwagner** [comment]
I'm inclined to think we should change read_table to read_csv in the datascience library.  I don't see any downside, as it seems to have the same functionality and is just a different name for the code; and it makes datascience work more cleanly with all versions of pandas, so it takes this issue off the table.

**Comment by adnanhemani** [comment]
I'm mainly scared of an API change on this function since it's so vital to this library and I don't understand the edge cases well enough - I have a feeling any change will affect the edge cases (non csv files that are currently supported). But I can work on a patch if everyone else thinks it might be best to switch over.

**Comment by deculler** [comment]
I think it is unlikely that pandas folks will remove non-csv functionality
from read_csv.  Too much already relies on that.  Certainly they won't
while still agonizing through this API change-or-not.  So I think we are
safe to make the switch while pandas settles down.  We will want to think
about passing kwargs through at some point.

**Comment by davidwagner** [comment]
Fixed by #362
