### ISSUE TITLE
ERROR: datascience 0.15.3 has requirement coverage==4.5.3

### ISSUE THREAD

**Issue by tbrown122387** [data-8/datascience#415]
pip install datascience yields

ERROR: datascience 0.15.3 has requirement coverage==4.5.3, but you'll have coverage 4.4 which is incompatible.

It isn't a fatal error, but it confuses students.

**Comment by adnanhemani** [comment]
Hi @tbrown122387 - I'm looking at our dependencies but I'm not seeing a strict requirement for coverage==4.5.3 anywhere...(I combed through the latest Travis CI builds as well to see if there's an implied dependency too. There isn't, Travis is installing Coverage v5.0 on its own.) Thus, my best guess is that it's an issue while installing locally/on a specific environment setup.

If you see somewhere that it's a problem with our library rather than an environment issue, please feel free to re-open this ticket and comment back with your findings/steps for reproducibility :)

**Comment by tbrown122387** [comment]
Thanks for looking into it @adnanhemani yes, most students are installing in an anaconda environment with either 

	activate base
	conda install pip
	pip install datascience
	pip install okpy
	
In a windows anaconda prompt or the following in a mac/Linux terminal
 
	source activate base
	conda install pip
	pip install datascience
	pip install okpy

How would this change the dependencies, though? Sorry, I’m not really a packaging expert

**Comment by adnanhemani** [comment]
Hi @tbrown122387, I tried to spin up a new conda env on my laptop with the scripts that your students are using...I'm not seeing that particular error.

One thing I do see, however, is that it seems that okpy is requiring Coverage@v4.4. Maybe that's causing the error that your students are seeing? Could you please try to see what version of datascience and pip your script is installing? I think a couple of versions back we had problems with dependencies and we made them laxer since.
