### ISSUE TITLE
supporting "windowing" functionalities by adding an index to the function passed to apply

### ISSUE THREAD

**Issue by yifanwu** [data-8/datascience#422]
Hi folks,

I have a use case where I need to check the row immediately after when running a custom apply

One idea I had was to access the row index when invoking the function during apply, which can be an easy addition of `enumerate` in the for loops applying the functions.
https://github.com/data-8/datascience/blob/master/datascience/tables.py#L359-L367

Does that sound reasonable? Or let me know fi there is another way to do it!

Thanks.

**Comment by adnanhemani** [comment]
HI @yifanwu, so I'm not exactly sure what you're trying to do - maybe an example for me to visualize might be helpful in me trying to help you find a solution to your needs. But if I'm reading this correctly, you might want to just append a new column to your table with `row_num` and set it equal to `np.arange(table.num_row)` - that way you can get the row index as part of the apply function? If you're doing this often, then this can easily be made into a function as well!

As for adding the enumerate to the `Table#apply` function, I don't think we're looking to change the expected behavior from any functions that we currently publish unless there's a clear and objective reason why the current behavior is incorrect. Sorry about that.

**Comment by yifanwu** [comment]
Hey Adnan, so this function crosses rows, not just a single row.

Here is an example (contrived abstraction from my actual use case, which requires more involved explanation)

```
t = Table().with_columns(
    'letter', make_array('a', 'b', 'c', 'a', 'b'),
    'count',  make_array(9, 3, 3, 1, 2),
    'points', make_array(1, 2, 2, 10, 1)
)
```
Now I want to create a new column that indicates if there was a transition from 'a' to 'b'.

I created the following work around, which works, but is pretty ugly.
```
def custom_fun(letter, index):
  if letter = "b" and index > 0 and t.row(index - 1).letter == "a":
     return True
  else:
     return False

t['a_to_b'] = np.array([custom_fun(action, index[0]) for index, action in np.ndenumerate(t['letter'])])
```
I guess it's just a matter what you would consider including in the API. Maybe it would be too advanced for an intro to DS course library (even DS100 doesn't teach windowing afaik).

**Comment by adnanhemani** [comment]
Hi @yifanwu , yeah so I don't think we're looking to support this type of windowing - afaik, SQL doesn't support this out of the box either and I don't remember Pandas doing so either.

I would suggest a speed optimization: maybe it might be faster for you to run your function by just iterating through the column values rather than calling `table.row` over and over again? As in something like this:

```
def transition_column(table, column, value_1, value_2):
	relevant_column = table.column(column)
	retVal = [None]
	for i in range(1, len(relevant_column)):
		if relevant_column[i-1] == value_1 and relevant_column[i-1] == value_2:
			retVal.append(True)
		else:
			retVal.append(False)
	return np.array(retVal)

t = t.with_column("a_to_b", transition_column(t, "letter", "a", "b"))
```

I'll keep this issue open for a bit to see if there's an unexpected surge in popularity for adding a feature like this, but if not, I'll close it after a while. Thanks for the suggestion though :)

**Comment by papajohn** [comment]
You could also join each row with the previous row, then everything you
need would be on one row.

**Comment by yifanwu** [comment]
Thanks @adnanhemani for the alt solution, though I'm just going to use mine for ease of understanding (at the cost of perf). Though re: SQL and Pandas, both support windowing (though windowing is not in the core relational alg) --- see https://www.postgresql.org/docs/9.1/tutorial-window.html and https://pandas.pydata.org/pandas-docs/stable/reference/window.html.

@papajohn, just to be sure for me to know the "previous row" I need to create a numeric 0-N index and then join on the calculation right?  Like the below?

```
t['index'] = np.arange(t.num_rows)
t['index_diff'] = t.apply(lambda x: x - 1, 'index')
t.join('index', t, 'index_diff')
```
Seems pretty elegant.

**Comment by papajohn** [comment]
Yep, that’s what I had in mind.

**Comment by davidwagner** [comment]
Good stuff.  Sounds like there are reasonable ways to do this with the APIs currently provided, and I don't see a compelling enough argument to add a new API, so I'm going to close this.  Thank you for the good discussion!
