### ISSUE TITLE
Breaking change from matplotlib??! Crash on "from datascience import *"

### ISSUE THREAD

**Issue by mdogy** [data-8/datascience#445]
Students checked the interactive version of Inferential Thinking:

https://www.inferentialthinking.com/chapters/01/3/Plotting_the_Classics.html

First cell crashes on

from datascience import *

Error message
----------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-6f3a305c96af> in <module>
----> 1 from datascience import *

/opt/tljh/user/lib/python3.7/site-packages/datascience/__init__.py in <module>
      1 from .version import __version__
      2 
----> 3 from .tables import *
      4 from .formats import *
      5 from .maps import *

/opt/tljh/user/lib/python3.7/site-packages/datascience/tables.py in <module>
     15 import numpy as np
     16 import matplotlib
---> 17 matplotlib.use('agg', warn=False)
     18 import matplotlib.pyplot as plt
     19 import pandas

TypeError: use() got an unexpected keyword argument 'warn'
---------------------

Local and binder version  matplotlib.__version__ == '3.3.1'  give same (same result)

**Comment by adityakuppa26** [comment]
@mdogy I see that the warn parameter has been deprecated following matplotlib3.1 and completely removed in 3.3.
`sys:1: MatplotlibDeprecationWarning: The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.`

If matplotlib could be downgraded to 3.2, this issue gets fixed. But i am not sure if we'd like to downgrade it. Please share your thoughts so that i could do the needful.

**Comment by mdogy** [comment]
I am using inferentialthinking to teach a course. That means that the "interact" links are broken. That makes adoption hard unless you are a school that has set up your own links to the book on your own binder. We have a jupyterhub but not a binder set up. 
I think priority 1 for data 8 is to make sure that people clicking the interact link don't see an error message. The last thing you want to show students as their first encounter with programming is a nasty error message! 
Next until you have a fix you might want to post where every people can see it the work around you suggest which is to downgrade to 3.2. Not sure I can do that because I am running 2 classes off the same kernel and one is using lots of packages. If it were just my data-8 like class, I guess it wouldn't be a big deal to try in conda. I could run two kernels but that creates complications.
As far as fixing the bug, temporarily at least, could you just drop the warn=False?

**Comment by adnanhemani** [comment]
Hi folks, turns out we had fixed and merged code for this (here's the code in question: https://github.com/data-8/datascience/blob/master/datascience/tables.py#L17) ....but forgot to push the new version of the code to PyPi. I don't have PyPi push access, but @davidwagner does. Could you please push our latest changes to PyPi?

**Comment by davidwagner** [comment]
I will work on this and get back to you shortly!

**Comment by davidwagner** [comment]
datascience 0.15.8 should fix this.  Update with pip.  I apologize for the issues you were experiencing.
