### ISSUE TITLE
Histogram Axis and Scatter Plot Points don't line up

### ISSUE THREAD

**Issue by Yanay1** [data-8/datascience#487]
A student on piazza pointed this out:
![image](https://user-images.githubusercontent.com/10257130/97492485-da79df00-1920-11eb-8b42-c238a29593e1.png)
![image](https://user-images.githubusercontent.com/10257130/97492494-dfd72980-1920-11eb-9246-a2db5fc14842.png)
When they specified bins, the axis did line up.

**Comment by adnanhemani** [comment]
This problem is underlying in matplotlib - and not a problem with datascience. What is happening here is that the new scatterplot that is added to the same axes is autoscaling incorrectly. This is a known issue: https://stackoverflow.com/questions/41675155/matplotlib-graph-with-same-data-doesnt-overlap

We're in a weird situation here now: since we're providing a wrapper on top of matplotlib, we can't file a bug report with matplotlib (as the SO article suggests - the matplotlib user can, in theory, rescale their own axis without issues); but every manual rescale needs to be done on a per-graph basis (there is no blanket solution for this rescaling). I think the best we can do is to change the assignment to rescale the axis manually using bins so as to not further confuse the students.

If anyone has a better idea, I'd love to hear it. I'll probably end up sending an email to the recent instructors who've used this project in their semesters to make this change if I don't hear from anyone else on this issue.

**Comment by davidwagner** [comment]
For future reference, the workaround for the old Data 8 Project 2 is to change

```
Table().with_column('Simulated distance to true incidence', diabetes_simulated_stats).hist()
plots.scatter(observed_diabetes_distance, 0, color='red', s=30)
```

to:

```
Table().with_column('Simulated distance to true incidence', diabetes_simulated_stats).hist(bins=np.arange(0, 0.02, 0.001))
plots.scatter(observed_diabetes_distance, 0, color='red', s=30)
```

**Comment by adnanhemani** [comment]
Thanks for the note @davidwagner! I've gotten this project is now retired, so I'll close this issue out.
