### ISSUE TITLE
Numpy Definition of Histogram Differs from Data 8 Definition

### ISSUE THREAD

**Issue by Yanay1** [data-8/datascience#493]
From numpy histogram documentation: https://numpy.org/doc/stable/reference/generated/numpy.histogram.html  

"All but the last (righthand-most) bin is half-open. In other words, if bins is:

[1, 2, 3, 4]
then the first bin is [1, 2) (including 1, but excluding 2) and the second [2, 3). The last bin, however, is [3, 4], which includes 4."

This is different from the definition we use in class where every bin is exclusive on the end.

**Comment by adnanhemani** [comment]
@Yanay1 - just to confirm, in class we're currently teaching the opposite bin theory? i.e. left-hand of the bin is exclusive and right-hand of the bin is inclusive? If so, is there a pedagogical reasoning for this?

The reason why I ask is because there's no easy patch for this. The best way I can tell is probably doing something similar to this: [https://stackoverflow.com/questions/62726096/excluding-rightmost-edge-in-numpy-histogram](https://stackoverflow.com/questions/62726096/excluding-rightmost-edge-in-numpy-histogram)...and it'd be a hassle to implement this all over the library (not to mention the risk of breaking current code that people have written with this library).

How big of a priority is this change for Data 8?

**Comment by Yanay1** [comment]
No, we still teach left side inclusive right side exclusive but the numpy definition has the right side of the last bin (ie the rightmost bin) as inclusive. It's not a huge issue but might cause some confusion for students.

**Comment by adnanhemani** [comment]
Oh I see. But I don't think we should change the definition - it makes more sense, in my opinion, to keep the last bucket inclusive as well to make sure that if a student uses the greatest possible value as the end of their bins, they'll get all possible values in their histogram.

I'm going to close this ticket for the time being (and to reduce clutter on this repo), but if this becomes a larger priority for Data 8 in the future, please feel free to reopen the ticket with some examples of assignments where this change could cause a difference and I'll try to find some way to make it work (if needed). Thanks!
