### ISSUE TITLE
Warnings in tests/plotly-charts.ipynb

### ISSUE THREAD

**Issue by davidwagner** [data-8/datascience#507]
`t.scatter("weight", ["hp", "displ"], group="origin")` and `t.scatter3d("weight", 'accel', ["hp", "displ"], group="origin")` yield the following warning:

`UserWarning: Group and overlay are incompatible in a scatter`

@khsu2000 or @chrispyles,  Any idea what is going on here?

**Comment by khsu2000** [comment]
@davidwagner From my investigation, this issue is caused by specifying multiple columns to plot against on the y-axis (`"hp"` and `"displ"`). This is because of the follow checks in `Table.scatter`, `Table.iscatter`, and `Table.iscatter3d`: https://github.com/data-8/datascience/blob/887e7275d593f928bcae4c86bdd2356c1bbd6ad7/datascience/tables.py#L3953-L3955

This warning also showed up for the non-interactive versions of the scatter plot during my testing. The default argument for `overlay` is True, so, when multiple columns are provided as the other axis, this condition is met and `overlay` is set to False along with this warning. The easiest way to suppress the warning would be to just remove the warning message while still silently setting `overlay` to False.

Please let me know if you want me to make this change.

**Comment by davidwagner** [comment]
Thanks for the diagnosis!  That makes sense.  I appreciate your help.  What would you recommend?  Do you see any value in that warning?  I'm struggling to find any situation where it is useful.

**Comment by AshiJoshi** [comment]
Hi @khsu2000 @davidwagner 
I wanted to get involved in the project and was scrolling through the issues. Is there a need for the warning? If not, can this issue be assigned to me?
Thanks!

**Comment by davidwagner** [comment]
@AshiJoshi @khsu2000 I would be fine with removing the warning.  Feel free to generate a pull request that does that.  (We don't assign issues, but just let anyone who wants contribute.)

**Comment by davidwagner** [comment]
Fixed in PR #593 by removing the warning.
