### ISSUE TITLE
`Table.scatter` method doesn't recognize `sizes` argument

### ISSUE THREAD

**Issue by willfurtado** [data-8/datascience#549]
## Problem

When developing Data 6 curriculum, I ran into a (supposed) error with the `Table.scatter` method. Despite there being a large range of possible values for `body_mass_g`, the `scatter` method seems to plot all points as the same marker size.
 
<img width="539" alt="Screen Shot 2022-07-10 at 5 43 39 PM" src="https://user-images.githubusercontent.com/56857749/178163067-31ca059d-b934-453a-90ca-81ffce2b8e39.png">

To replicate this, you can run the following:
```python
from datascience import *
import seaborn as sns
%matplotlib inline

penguins = Table.from_df(sns.load_dataset("penguins"))

penguins.scatter('bill_length_mm', 'bill_depth_mm', 
                 group = 'species', sizes = 'body_mass_g')
```

**Comment by adnanhemani** [comment]
Hi Will,

There's actually no bug - the issue is the differences between the datapoints is very small in the grand scheme of things, so while there is scaling happening technically, the scaling is too undetectable to tell. For example, look at this sample codeI used to test where I inserted a massive datapoint into the dataset and that point would cause the other datapoints to scale to being much smaller.

```
from datascience import *
import seaborn as sns
%matplotlib inline

penguins = Table.from_df(sns.load_dataset("penguins"))

penguins = penguins.with_row(["Adnan", "Adnan", 35, 14, 190, 10000000, "Male"])
penguins.scatter('bill_length_mm', 'bill_depth_mm', group = 'species', sizes = 'body_mass_g')
```

![Screen Shot 2022-07-10 at 8 11 14 PM](https://user-images.githubusercontent.com/10746770/178181706-e960c30c-922a-4a1b-8475-04ebccd41b0d.png)

This is also as a result of `matplotlib`, as our visualizations are mostly a layer of abstraction on top of `matplotlib`. For this specific option, we are simply providing the `sizes` argument directly to the `matplotlib` library (https://github.com/data-8/datascience/blob/master/datascience/tables.py#L4093).

If I've missed something, please let me know by re-opening this ticket! Thanks for reporting this :)

**Comment by willfurtado** [comment]
Got it! Thanks so much for going out of your way to point this out -- I appreciate it.
