### ISSUE TITLE
0.17.6 release not on pypi or conda

### ISSUE THREAD

**Issue by taylorgibson** [data-8/datascience#581]
Latest version of `datascience` available on PyPI and conda forge is `0.17.5`, while `0.17.6` is the most recent release per `CHANGELOG.md`.  Can version `0.17.6` be built and pushed out? 

![image](https://user-images.githubusercontent.com/5053805/217911954-52b5c82b-5d1b-4012-a24c-5a865e246380.png)

Additionally, I believe building a `py3-none-any` type wheel file like was done in `0.17.2` would also help make this version installable in jupyterlite. Jupyterlite/pyiodide can currently only `%pip install datascience` with version `0.17.2`, but this version has several breaking issues with current versions of Python, so installing it is not currently useful.

![image](https://user-images.githubusercontent.com/5053805/217911530-069fe87f-4c5e-4d2c-af75-a4a8ccc76734.png)

![image](https://user-images.githubusercontent.com/5053805/217911706-f24d9179-e057-4e7c-9a7d-425972490989.png)
![image](https://user-images.githubusercontent.com/5053805/217911744-2805514b-7df8-4688-91eb-82f5bde7c35a.png)

**Comment by adnanhemani** [comment]
Hi, there aren't any major functionality differences between 0.17.5 and 0.17.6 yet, so we've kept the 0.17.6 release open for improvements still. Once we decide to lock the release, we will push to PyPi.

Unfortunately I'm not sure about the `py3` wheel - I'll let @davidwagner comment about that.

**Comment by taylorgibson** [comment]
Thanks @adnanhemani for that update re: 0.17.6; makes sense.

**Comment by adnanhemani** [comment]
I believe [this](https://github.com/data-8/datascience/issues/522) might have been the ticket that was used to push the wheel for 0.17.2.

@davidwagner - whenever you get a chance, if you could please try to upload the wheel for 0.17.5 as well using the commands on the above ticket, that might be useful!

**Comment by davidwagner** [comment]
Done.  I wasn't confident about my ability to push this for older versions and get exactly the right version, so I've pushed version 0.17.6, with both a sdist and a wheel.  Let's target any future improvements/bugfixes for 0.17.7.  If you update to `datascience==0.17.6`, I think you should be able to install from wheel.

Also, to try to avoid this happening again, I've updated our instructions in DEVELOPERS.md with the proper procedure, so that I always push a wheel in the future for all future releases.  Sorry about the delay getting this in place.

**Comment by taylorgibson** [comment]
Thanks @davidwagner  I can confirm it's up and running and appears to be working in Jupyterlite. Thanks!

![image](https://user-images.githubusercontent.com/5053805/220760614-c658bdfe-9a61-46ed-a6fa-7e0e6561265e.png)
